#!/bin/bash

# Display all active IPv4 addresses on the machine
# Compatible with macOS, using ifconfig and awk

# Use ifconfig to display network interfaces and their IP addresses
ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}'
